import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { HeaderComponent, FooterComponent } from "./shared_components/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next JS- Learning demo", // Default title for an app where explicitly title is not defined
    template: "%s | NextJS" // for displaying dynamic titles, applied to child segments only & not to in which it is defined
                            // here, %s will be replaced by string that will be passed from child components, if title is explicitly specified
                            // like here in "profile" component
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderComponent />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
